# Generated by Django 5.2.6 on 2025-09-23 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_rename_user_recipient_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingattempt",
            name="recipient",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.recipient",
            ),
            preserve_default=False,
        ),
    ]
